# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jake Hosen
tagline:          'Freshwater Microbial Ecology & Biogeochemistry'
description:      '<p>Postdoctoral Associate</p> <p>Raymond Lab: Yale School of Forestry & Environmental Studies'
url:              http://jakehosen.github.io
baseurl:          /

author:
  name:           'Jake Hosen'
  url:            https://twitter.com/jakehosen

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
