# Dependencies
# markdown:         redcarpet
#highlighter:      pygments

# Permalinks
permalink:        none
#relative_permalinks: true

# Setup
title:            Jake Hosen
tagline:          'Freshwater Microbial Ecology & Biogeochemistry'
description:      '<p>Postdoctoral Associate</p> <p><a href="http://environment.yale.edu/raymond-lab/">Raymond Lab</a>:<br> Yale School of Forestry & Environmental Studies</p> <p><a href="mailto:jake.hosen@yale.edu">E-Mail</a><br><a href="/files/Hosen_CV_20180320.pdf">C.V.</a><br><a href="http://www.researchgate.net/profile/Jacob_Hosen">Research Gate</a><br><a href="https://scholar.google.com/citations?user=vsRFxUEAAAAJ&hl=en">Google Scholar</a><br><a href="http://www.twitter.com/jakehosen">Twitter</a>'
url:              http://jakehosen.github.io
baseurl:          /

author:
  name:           'Jake Hosen'
  url:            https://twitter.com/jakehosen

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
