<style>
  .col2 {
    columns: 2 200px;         /* number of columns and width in pixels*/
    -webkit-columns: 2 200px; /* chrome, safari */
    -moz-columns: 2 200px;    /* firefox */
    vertical-align: middle;
  }
  .col3 {
    columns: 3 100px;
    -webkit-columns: 3 100px;
    -moz-columns: 3 100px;
  }
</style>

---
title: Farmington at Tariffville Data
output: html_document
---

<div class="col2">
 
```{r, fig.width=4, fig.height=4.3,echo=FALSE,out.extra='style="float:right"'}
dygraph(farm_cdom1,group="farm",ylab="CDOM (QSU)",width=440,height=280)  %>% 
    dyRangeSelector()  %>% 
	 dyOptions(drawGrid = FALSE, drawPoints=TRUE,pointSize=2,strokeWidth=0) %>% 
  dyCrosshair(direction = "vertical")
```
 
```{r, fig.width=4, fig.height=4.3,echo=FALSE,out.extra='style="float:right"'}
dygraph(farm_turb,group="farm",ylab="Turbidity (NTU)",width=440,height=280)  %>% 
    dyRangeSelector()  %>% 
	  dyAxis("y", label = "Turbidity (NTU)", valueRange = c(0, 1000)) %>%
	 dyOptions(drawGrid = FALSE, drawPoints=TRUE,pointSize=2,strokeWidth=0) %>% 
  dyCrosshair(direction = "vertical")
```
</div>


<div class="col2">
 
```{r, fig.width=4, fig.height=4.3,echo=FALSE,out.extra='style="float:right"'}
dygraph(farm_cond,group="farm",ylab="Conductivity (uS/cm)",width=450,height=300)  %>% 
    dyRangeSelector()  %>% 
	 dyOptions(drawGrid = FALSE) %>% 
  dyCrosshair(direction = "vertical")
```
 
```{r, fig.width=4, fig.height=4.3,echo=FALSE,out.extra='style="float:right"'}
dygraph(farm_dis,group="farm",ylab="Discharge (CFS/sec)",width=450,height=300)  %>% 
    dyRangeSelector()  %>% 
	 dyOptions(drawGrid = FALSE) %>% 
  dyCrosshair(direction = "vertical")
```
</div>
